### ISSUE TITLE
Check whether Facebook and Twitter settings are saved when in Gutenberg

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#19]
Check whether Facebook and Twitter settings are saved when in Gutenberg.

**Comment by igorschoester** [comment]
Free
---
- [x] Facebook image
- [x] Facebook title
- [x] Facebook description
- [x] Twitter image
- [x] Twitter title
- [x] Twitter description

Premium
---
- [x] Facebook image
- [x] Facebook title
- [x] Facebook description
- [x] Twitter image
- [x] Twitter title
- [x] Twitter description

**Comment by igorschoester** [comment]
Free
---
- [ ] Focus keyword

Premium
---
- [ ] Focus keyword
