### ISSUE TITLE
Fix colors of analysis bullets

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#24]
Currently, all bullets are grey. Make sure they are red, orange, green and light grey again.
<img width="498" alt="schermafbeelding 2018-02-28 om 10 31 45" src="https://user-images.githubusercontent.com/17744553/36780203-983e4886-1c72-11e8-9584-acc5317a79b5.png">
If you think the styling from Gutenberg is too aggressive, and this should be fixed in Gutenberg instead of in wordpress-seo, please create an issue on their repo.

**Comment by IreneStr** [comment]
@afercia Created an issue on the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/5302

The color of the eye icon in the eye buttons is probably related:
<img width="594" alt="schermafbeelding 2018-02-28 om 14 43 25" src="https://user-images.githubusercontent.com/17744553/36790616-c065cad2-1c95-11e8-8c87-ab2540cc9886.png">

**Comment by afercia** [comment]
Related Gutenberg PR: https://github.com/WordPress/gutenberg/pull/5352

**Comment by afercia** [comment]
New Gutenberg PR by @jasmussen https://github.com/WordPress/gutenberg/pull/5496
