### ISSUE TITLE
Investigate whether the focus keyword is saved 

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#26]
Investigate whether the focus keyword is saved: fill in a focus keyword in Gutenberg, save and open the post in the classic editor, and vice versa. 

Don't forget about multiple keywords in Premium.

**Comment by igorschoester** [comment]
The [update button](https://github.com/WordPress/gutenberg/blob/9c6143b47b980f79c34a2230874bc5636c1a71ef/editor/components/post-publish-button/index.js#L40) in Gutenberg is staying disabled where before you could always update.

Free
---
- [ ] Focus keyword

Premium
---
- [ ] Focus keyword
