### ISSUE TITLE
Fix cornerstone checkbox styling

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#27]
Both the checkbox and the label should be located below the keyword input field. 
<img width="521" alt="schermafbeelding 2018-02-28 om 10 37 50" src="https://user-images.githubusercontent.com/17744553/36780494-75b0de7c-1c73-11e8-9923-a82ffa59f410.png">
If you think the styling from Gutenberg is too aggressive, and this should be fixed in Gutenberg instead of in wordpress-seo, please create an issue on their repo.

**Comment by igorschoester** [comment]
Found the [cause](https://github.com/Yoast/gutenberg/blob/master/edit-post/components/meta-boxes/meta-boxes-area/style.scss#L45).
```css
.edit-post-meta-boxes-area input {
    max-width: 300px;
}
```

**Comment by IreneStr** [comment]
Will be fixed if https://github.com/WordPress/gutenberg/pull/5464 is merged in Gutenberg
