### ISSUE TITLE
Fix premium keyword close button icon

### ISSUE THREAD

**Issue by igorschoester** [Yoast/gutenberg#28]
Currently the close button does not look very good.
<img width="553" alt="screen_shot_2018-02-28_at_11_06_17" src="https://user-images.githubusercontent.com/35524806/36782100-1cca2ff2-1c78-11e8-9fd8-92fec01e6840.png">

Without Gutenberg it looks like this:
<img width="537" alt="screen_shot_2018-02-28_at_11_12_18" src="https://user-images.githubusercontent.com/35524806/36782217-8768a8f2-1c78-11e8-9608-e67b66ad73f2.png">

Before doing this: check the result of the [grey dots issue](https://github.com/Yoast/gutenberg/issues/25). This might have changed things for the better already.

**Comment by afercia** [comment]
Root cause: Gutenberg switches everything to `box-sizing: border-box` 😬  

```
.gutenberg * {
    box-sizing: border-box;
}
```

**Comment by afercia** [comment]
See related Gutenberg issue: https://github.com/WordPress/gutenberg/issues/5353

**Comment by igorschoester** [comment]
[Branch: update/metaboxes-box-sizing](https://github.com/Yoast/gutenberg/tree/update/metaboxes-box-sizing)

**Comment by igorschoester** [comment]
PR: https://github.com/WordPress/gutenberg/pull/5433
