### ISSUE TITLE
Fix coloring of the need help icons.

### ISSUE THREAD

**Issue by igorschoester** [Yoast/gutenberg#29]
Currently the need help icons are blue:
<img width="245" alt="screen_shot_2018-02-28_at_11_19_25" src="https://user-images.githubusercontent.com/35524806/36782465-5cd8dee4-1c79-11e8-9d97-7c07d618d7f4.png">

They should look like this:
<img width="537" alt="screen_shot_2018-02-28_at_11_12_18" src="https://user-images.githubusercontent.com/35524806/36782389-1b2ca002-1c79-11e8-8097-3b0cb551818c.png">

**Comment by afercia** [comment]
See related Gutenberg PR https://github.com/WordPress/gutenberg/pull/5352 it will solve the issue if accepted.

**Comment by afercia** [comment]
New Gutenberg PR by @jasmussen https://github.com/WordPress/gutenberg/pull/5496
