### ISSUE TITLE
Gutenberg CSS conflicts

### ISSUE THREAD

**Issue by afercia** [Yoast/gutenberg#30]
See also https://github.com/Yoast/gutenberg/issues/24 https://github.com/Yoast/gutenberg/issues/27 https://github.com/Yoast/gutenberg/issues/25 https://github.com/Yoast/gutenberg/issues/29

The Gutenberg stylesheet targets some generic elements a big aggressively, using selectors with high specificity. This produces some CSS conflicts in the metabox. In addition to the ones addressed in the issues above, here's some more conflicts noticed so far:

radio buttons become a semi-squared and their border color changes:

<img width="393" alt="screen shot 2018-03-01 at 09 08 02" src="https://user-images.githubusercontent.com/1682452/36837180-e8cc5eea-1d3b-11e8-8d64-fd284fb0e60d.png">

input fields: their size is altered, they get a different line-height and padding:

<img width="376" alt="screen shot 2018-03-01 at 10 21 25" src="https://user-images.githubusercontent.com/1682452/36837276-31ad06aa-1d3c-11e8-8b36-0c726e893345.png">

their focus style is pretty ok but when hovered with the mouse the border color becomes too light:

<img width="371" alt="screen shot 2018-03-01 at 10 21 33" src="https://user-images.githubusercontent.com/1682452/36837304-45ead264-1d3c-11e8-9d1a-42b5b9824374.png">

Fixing all these cases in our stylesheets is certainly possible, however we should consider to ask the Gutenberg project to lower their selectors specificity or establish solid conventions to avoid conflicts as much as possible.

**Comment by IreneStr** [comment]
Closed in favor of https://github.com/Yoast/gutenberg/issues/43
