### ISSUE TITLE
Fix font color

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#35]
In the classic editor metabox, the default font color is `#444`. In the Gutenberg metabox, this has changed to #555d66.

At least the following parts of our metabox are affected:
- The snippet preview editor headers (title, slug, meta description);
- The cornerstone checkbox label
- All text on the social tab, including the upsell to premium.

**Comment by IreneStr** [comment]
Please also make sure the font color in the help center and advanced tab is correct. The Insights box in Premium should have the correct font color as well.

**Comment by danielFangstrom** [comment]
Gutenberg PR https://github.com/WordPress/gutenberg/pull/5563
