### ISSUE TITLE
Fix input field heights

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#36]
The height of all input fields in the metabox is too high. 

## Example: Focus keyword input field
<img width="653" alt="schermafbeelding_2018-03-12_om_09_08_14" src="https://user-images.githubusercontent.com/17744553/37271895-2203c652-25d5-11e8-9105-c06821874d87.png">
<img width="542" alt="schermafbeelding_2018-03-12_om_09_08_33" src="https://user-images.githubusercontent.com/17744553/37271927-430e34ea-25d5-11e8-94b6-fd2c735407ed.png">

Possible source: `line-height: 24px;` on `.edit-post-meta-boxes-area input, .edit-post-meta-boxes-area select, .edit-post-meta-boxes-area textarea` 

### Snippet editor:
<img width="514" alt="schermafbeelding 2018-03-12 om 09 15 20" src="https://user-images.githubusercontent.com/17744553/37272213-42675f7a-25d6-11e8-988a-69cd0296a94c.png">

### Social tab:
<img width="530" alt="schermafbeelding 2018-03-12 om 09 15 28" src="https://user-images.githubusercontent.com/17744553/37272232-58c52e3c-25d6-11e8-8c7e-9581b216e34d.png">

### Advanced tab: 
<img width="505" alt="schermafbeelding 2018-03-12 om 09 16 23" src="https://user-images.githubusercontent.com/17744553/37272214-45183a50-25d6-11e8-9bb1-44f6d48a40f5.png">

## Please note
- The above list might not include all occurrences. Please walk through the metabox to double check all input fields.
- Please also check YoastSEO premium.
- The rounded corners are not part of this issue: https://github.com/Yoast/gutenberg/issues/37

**Comment by afercia** [comment]
Related Gutenberg issues:
https://github.com/WordPress/gutenberg/issues/5482
https://github.com/WordPress/gutenberg/issues/4963

**Comment by afercia** [comment]
See Gutenberg PR: https://github.com/WordPress/gutenberg/pull/5561
