### ISSUE TITLE
Remove rounded corners from input fields

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#37]
All input fields in the metabox have rounded corners, but they should't. This is the case for both text input fields as well as checkboxes:
<img width="542" alt="schermafbeelding_2018-03-12_om_09_08_33" src="https://user-images.githubusercontent.com/17744553/37273492-5388aa08-25da-11e8-89c1-a6a135a0278c.png">
<img width="674" alt="schermafbeelding_2018-03-12_om_09_46_42" src="https://user-images.githubusercontent.com/17744553/37273625-a91acc44-25da-11e8-9bcb-23e72371fcbf.png">

Please walk through Free and Premium to make sure you've fixed all input fields.

**Comment by afercia** [comment]
Related Gutenberg issues:
https://github.com/WordPress/gutenberg/issues/5482
https://github.com/WordPress/gutenberg/issues/4963

**Comment by afercia** [comment]
See Gutenberg PR: https://github.com/WordPress/gutenberg/pull/5561
