### ISSUE TITLE
Metabox width is restricted to 636px

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#38]
In Gutenberg, the meta box width is restructed to 636 px.
<img width="954" alt="schermafbeelding 2018-03-12 om 10 22 32" src="https://user-images.githubusercontent.com/17744553/37275697-3736c6ae-25e0-11e8-8bf1-39d31e95274a.png">

However, in the classic editor, the meta box width is 100% of #post stuff:
<img width="391" alt="schermafbeelding 2018-03-12 om 10 28 41" src="https://user-images.githubusercontent.com/17744553/37275709-3fed5362-25e0-11e8-81f2-2b6522915301.png">

This results in much higher widths in full screen. For example, the metabox width is 1619px in this screenshot:
<img width="1657" alt="schermafbeelding 2018-03-12 om 10 28 35" src="https://user-images.githubusercontent.com/17744553/37275707-3e69db0a-25e0-11e8-84dc-4f26d3473358.png">

Because of the limited metabox width in Gutenberg, several things in WordPress SEO break out of the metabox, or are distorted in other ways.

## Help center distortions
- Not all help center tabs fit next to each other. 
<img width="620" alt="schermafbeelding 2018-03-12 om 10 39 12" src="https://user-images.githubusercontent.com/17744553/37276303-a00002bc-25e1-11e8-96fa-c9b8d60cc0cb.png">

- In addition, the paragraphs on the video tab are not visible, and there is a lot of whitespace below the video.
<img width="632" alt="schermafbeelding 2018-03-12 om 10 36 28" src="https://user-images.githubusercontent.com/17744553/37276145-406800e8-25e1-11e8-95c0-b7091c49bc47.png">

- The search bar is very small.
<img width="580" alt="schermafbeelding 2018-03-12 om 10 42 29" src="https://user-images.githubusercontent.com/17744553/37276488-18237738-25e2-11e8-98ee-ebe51959ae91.png">

## YoastSEO Premium distortions
Even in full screen, not all focus keyword tabs fit next to each other.
<img width="667" alt="schermafbeelding 2018-03-12 om 10 46 01" src="https://user-images.githubusercontent.com/17744553/37276633-946a67a2-25e2-11e8-94d2-d3c56941ee73.png">

## Please note
- The effects of the metabox width restriction might not be limited to the above list. Please walk through our metabox (free and premium) to double check everything.

**Comment by afercia** [comment]
Hm worth considering to ask the Gutenberg team to consider to give the meta boxes area all the available width. I guess this issue is of interest for all plugins.

**Comment by afercia** [comment]
Gutenberg issue: https://github.com/WordPress/gutenberg/issues/5562

**Comment by afercia** [comment]
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/5565
