### ISSUE TITLE
Fix social tab premium upsell alignment

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#39]
The upsell to premium is not aligned properly in Gutenberg:
<img width="700" alt="schermafbeelding 2018-03-12 om 10 51 23" src="https://user-images.githubusercontent.com/17744553/37276896-6c79e73a-25e3-11e8-9858-cd326c5472f1.png">

Classic editor:
<img width="928" alt="schermafbeelding 2018-03-12 om 10 52 04" src="https://user-images.githubusercontent.com/17744553/37276897-6d7af944-25e3-11e8-9f72-69bf6e7c19d8.png">

Please make sure it'll also work when the metabox has a greater width again: https://github.com/Yoast/gutenberg/issues/38.

**Comment by afercia** [comment]
Interestingly, seems the Gutenberg page doesn't have a container with a `.wrap` CSS class. This "wrap" container is pretty standard in WordPress and some styles depend on it. Coincidentally, the notices margin is one of them.

**Comment by maartenleenders** [comment]
We fixed this in WP SEO, because using the notice inside the metabox is something we did specifically as Yoast, so this is not a Gutenberg metabox issue. I think.
