### ISSUE TITLE
Radio buttons are not circular

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#40]
In Gutenberg, the meta box radio buttons are squared with rounded corners:
<img width="686" alt="schermafbeelding_2018-03-12_om_11_19_45" src="https://user-images.githubusercontent.com/17744553/37278332-b37c1e42-25e7-11e8-84ab-b9976617ce44.png">

However, in the classic editor they are circular:
<img width="837" alt="schermafbeelding_2018-03-12_om_11_21_02" src="https://user-images.githubusercontent.com/17744553/37278405-e2fc3aee-25e7-11e8-8600-1f0df8310673.png">

We should make sure they are circular in Gutenberg as well.

**Comment by afercia** [comment]
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/5561
