### ISSUE TITLE
Fix input field padding

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#41]
Classic editor:
<img width="567" alt="schermafbeelding 2018-03-12 om 11 33 30" src="https://user-images.githubusercontent.com/17744553/37278839-4689433a-25e9-11e8-9105-4bbc8e680f8a.png">
<img width="194" alt="schermafbeelding 2018-03-12 om 11 36 43" src="https://user-images.githubusercontent.com/17744553/37278978-aa29dc10-25e9-11e8-95df-7d7571ef6d33.png">
<img width="351" alt="schermafbeelding 2018-03-12 om 11 33 44" src="https://user-images.githubusercontent.com/17744553/37278844-48a0b9a0-25e9-11e8-803b-bff6d33d5e06.png">

Gutenberg: 
<img width="498" alt="schermafbeelding 2018-03-12 om 11 35 20" src="https://user-images.githubusercontent.com/17744553/37279000-b7ecaa12-25e9-11e8-865d-9a0ab85b6a6a.png">
<img width="207" alt="schermafbeelding 2018-03-12 om 11 35 54" src="https://user-images.githubusercontent.com/17744553/37279020-c676b992-25e9-11e8-9b1c-ec6da8959787.png">
<img width="388" alt="schermafbeelding 2018-03-12 om 11 36 18" src="https://user-images.githubusercontent.com/17744553/37278997-b4cb3ccc-25e9-11e8-8bf5-f42a511043d1.png">

**Comment by afercia** [comment]
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/5561
