### ISSUE TITLE
Fix input field focus style

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#42]
The focus style color of input fields in Gutenberg is some greyish blue.

Classic editor:
<img width="635" alt="schermafbeelding 2018-03-12 om 11 39 13" src="https://user-images.githubusercontent.com/17744553/37279092-0c4f523a-25ea-11e8-90b3-d3e218b86f10.png">

Gutenberg:
<img width="508" alt="schermafbeelding 2018-03-12 om 11 39 06" src="https://user-images.githubusercontent.com/17744553/37279091-0b2d05fa-25ea-11e8-8b9e-16caba6d9caa.png">

**Comment by afercia** [comment]
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/5561
