### ISSUE TITLE
Fix radio button size

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#45]
In the Gutenberg metabox, the radio buttons have a height and width of 16px, which causes the selection dot to be off-center:
<img width="348" alt="schermafbeelding 2018-03-16 om 11 19 48" src="https://user-images.githubusercontent.com/17744553/37515877-8e48f5b4-290c-11e8-95a8-6c9c67b937dd.png">

Classic editor: 
<img width="350" alt="schermafbeelding 2018-03-16 om 11 25 25" src="https://user-images.githubusercontent.com/17744553/37515946-dd63dd44-290c-11e8-9e1f-eb8ce55d023a.png">
The above screenshots are from the Advanced tab in the metabox.

Please figure out what in Gutenberg causes the greater height and fix it there.

**Comment by danielFangstrom** [comment]
Related Gutenberg PR: https://github.com/WordPress/gutenberg/pull/5690
