### ISSUE TITLE
Prevent snippet preview from breaking out of section

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#49]
<img width="722" alt="schermafbeelding_2018-03-16_om_16_16_20" src="https://user-images.githubusercontent.com/17744553/37528667-8465e0ba-2935-11e8-9a70-85a3ee7afd03.png">

**Comment by igorschoester** [comment]
Fixed by: https://github.com/Yoast/wordpress-seo/pull/9280
