### ISSUE TITLE
Add taxonomy data to selectors data API

### ISSUE THREAD

**Issue by atimmer** [Yoast/gutenberg#5]
Every plugin should be able to retrieve the data of taxonomies. This means:

* Categories
* Tags
* Custom taxonomies

A taxonomy has terms. For every term we need to know at least the following:

* Title
* Slug
* Is it active for the current post?

Please add any other data you can find in Gutenberg as well.

[Pull Request](https://github.com/WordPress/gutenberg/pull/5176)

**Comment by igorschoester** [comment]
Branch: [add/taxonomy-selector](https://github.com/Yoast/gutenberg/tree/add/taxonomy-selector)

**Comment by IreneStr** [comment]
PR: https://github.com/WordPress/gutenberg/pull/5176

**Comment by Xyfi** [comment]
Closing in favour of wordpress/gutenberg#5219
