### ISSUE TITLE
Pass props from Slot to Fills.

### ISSUE THREAD

**Issue by Xyfi** [Yoast/gutenberg#50]
## Issue Overview

We need a way for props to be passed from Slots to Fills.

## Possible Solution

This has been discussed with @youknowriad (Riad), and for now, the best solution would be a prop on the Slot component (`fillProps`) that is passed as props to the Fill component, which can be accessed by a function within the Fill component.

#### Slot
```jsx
<Slot fillProps={ propsToInject } />
```

#### Fill
```jsx
<Fill name="myslotname">
   { ( argsInjectedBySlots ) => () }
</Fill>
```

This can be achieved like this:
```js
// within the Fill render function:
if ( typeof this.props.children === 'function' ) {
  return this.props.children( argsInjectedBySlots );
}
```

https://wordpress.slack.com/archives/C02QB2JS7/p1521445850000061

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by IreneStr** [comment]
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/5711/files

**Comment by IreneStr** [comment]
Test code in layout/index.js:
```
			<Slot name="testSlot" bubblesVirtually fillProps={ { onClose: () => { console.log( "hoi" ) } } }/>
			<Fill name="testSlot">
				{ ( props ) => { props.onClose(); return null } }
			</Fill>
```
