### ISSUE TITLE
Create Screen takeover plugin API using react-modal

### ISSUE THREAD

**Issue by Xyfi** [Yoast/gutenberg#59]
I've created a branch with all necessary infrastructure for the Screen takeover plugin API.

add/slot-fill-screen-takeover-api

Take this and write an implementation of the screen takeover API using `react-modal`.

Related: #58

gutenberg-pr: https://github.com/WordPress/gutenberg/pull/6241

**Comment by IreneStr** [comment]
Branch: 59-react-modal-screen-takeover

It should look like this:
https://cloudup.com/cRhqngZCduC

To do (possibly incomplete):
- Close button should be an X
- Title should be a header

**Comment by IreneStr** [comment]
Please rename the branch to `try/react-modal-screen-takeover`

**Comment by boblinthorst** [comment]
```

**Comment by boblinthorst** [comment]
Is replaced by #64
