### ISSUE TITLE
Investigate whether it's possible to pin a sidebar by default

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#70]

**Comment by atimmer** [comment]
Yes, this is possible. By using `wp.data.dispatch( "core/edit-post" ).togglePinnedPluginItem( "[plugin-name]" )` you can toggle whether a plugin is pinned.

With `wp.data.select( "core/edit-post" ).isPluginItemPinned( "[plugin-name]" );` you can check if a plugin is currently pinned.
