### ISSUE TITLE
Overwrite the Gutenberg category component by own category component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#73]
Make it possible to overwrite the Gutenberg category component by our own category component including primary category (using slot-fill?)

**Comment by atimmer** [comment]
This is how our primary category integration looks like in the classic editor:

<img width="293" alt="screen shot 2018-07-03 at 10 51 21" src="https://user-images.githubusercontent.com/584693/42209496-130c9ad8-7eaf-11e8-9f4e-bc8d857abfe6.png">

There it is hacked in using jQuery, but this is obviously not a solution in Gutenberg.

**Comment by IreneStr** [comment]
We've decided to integrate a primary category picker in the sidebar, independent of Wordpress's/Gutenberg's category picker.
