### ISSUE TITLE
Add filter to overwrite Gutenberg's category component

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#75]
Add a filter to Gutenberg, similar to https://github.com/WordPress/gutenberg/pull/8225, to make it possible to overwrite Gutenberg's category component: 
<img width="280" alt="schermafbeelding 2018-08-09 om 12 15 22" src="https://user-images.githubusercontent.com/17744553/43893028-e9b7e71e-9bcd-11e8-9107-b30a9e44946a.png">

## Context
We want to be able to overwrite the component by the component itself + a dropdown to pick a primary category. 

## NB
The replacement itself will be handled in a separate issue on wordpress-seo.

**Comment by Xyfi** [comment]
Closing because the aforementioned filter already exists.
